project_name: relaygram
builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
      - "mips"
    gomips:
      - hardfloat
      - softfloat

    mod_timestamp: '{{ .CommitTimestamp }}'
