name: CI

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v1
      with:
        xgo_version: latest
        go_version: 1.17
        dest: dist
        prefix: relaygram
        targets: windows/386,windows/amd64,windows/arm64,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64,darwin/arm64
        ldflags: -s -w
        buildmode: default

    - uses: actions/upload-artifact@v2
      with:
        path: dist/
