name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=all --bare -t latest,${{ github.ref_name }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
